@extends('layouts.master')
@section('head')
  @include('layouts.css')
  @include('layouts.script')
  @include('layouts.navbar')
@endsection
@section('gallery')
    @include('diagnostyka.carousel')
@endsection
@section('body')
  @include('diagnostyka.body')
@endsection
@section('footer')
  @include('layouts.footer')
@endsection
