@extends('layouts.master')
@section('head')
  @include('layouts.css')
  @include('layouts.script')
    @include('layouts.navbar')
@endsection
@section('gallery')
    @include('layouts.carousel')
@endsection
@section('body')
  @include('layouts.body-index')
@endsection
@section('footer')
  @include('layouts.footer')
@endsection
